pipeline:
  name: Saudamini_demo
  identifier: Saudamini_demo
  projectIdentifier: default_project
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: approve
        identifier: approve
        description: ""
        type: Approval
        spec:
          execution:
            steps:
              - step:
                  name: approvepipeline
                  identifier: approvepipeline
                  type: HarnessApproval
                  timeout: 1d
                  spec:
                    approvalMessage: |-
                      Please review the following information
                      and approve the pipeline progression
                    includePipelineExecutionHistory: true
                    approvers:
                      minimumCount: 1
                      disallowPipelineExecutor: false
                      userGroups:
                        - saudamini
                    isAutoRejectEnabled: false
                    approverInputs: []
        tags:
          QA: ""
        when:
          pipelineStatus: Success
    - stage:
        name: build_saudamini
        identifier: build_saudamini
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          caching:
            enabled: true
            override: true
          buildIntelligence:
            enabled: true
          infrastructure:
            type: KubernetesDirect
            spec:
              connectorRef: kubernetesdelegate8466b558cfqtgbn
              namespace: default
              automountServiceAccountToken: true
              nodeSelector: {}
              os: Linux
          execution:
            steps:
              - step:
                  type: BuildAndPushDockerRegistry
                  name: BuildAndPushDockerRegistry_1
                  identifier: BuildAndPushDockerRegistry_1
                  spec:
                    connectorRef: saudu_docker
                    repo: daminiy5/saudu_docker_harness
                    tags:
                      - latest
                    dockerfile: .harness/orgs/default/projects/default_project/pipelines/Dockerfile
    - stage:
        name: Deploy_dev
        identifier: Deploy_dev
        description: ""
        type: Deployment
        spec:
          deploymentType: Kubernetes
          service:
            serviceRef: deploy_service_dev_SD
            gitBranch: dev
          environment:
            environmentRef: saudu_env
            gitBranch: dev
            deployToAll: false
            infrastructureDefinitions:
              - identifier: saudu_dev_infra
          execution:
            steps:
              - step:
                  name: Rollout Deployment
                  identifier: rolloutDeployment
                  type: K8sRollingDeploy
                  timeout: 10m
                  spec:
                    skipDryRun: false
                    pruningEnabled: false
                    delegateSelectors:
                      - kubernetes-delegate
            rollbackSteps:
              - step:
                  name: Rollback Rollout Deployment
                  identifier: rollbackRolloutDeployment
                  type: K8sRollingRollback
                  timeout: 10m
                  spec:
                    pruningEnabled: false
        tags: {}
        failureStrategies:
          - onFailure:
              errors:
                - AllErrors
              action:
                type: StageRollback
  properties:
    ci:
      codebase:
        connectorRef: test
        repoName: HelloWorld
        build: <+input>
